[TOAZ-101] Add support for a Cromwell landing zone
DataBiosphere/terra-cloud-resource-lib pull request #139
Opened 2022-08-02 19:22 UTC by jordansafer

Added a new factory for a Cromwell landing zone. The landing zone contains these resources:
- AKS Cluster, Storage Account, Batch Account, PostgreSQL server, Azure Relay
- VNet with 4 subnets: AKS subnet, compute subnet, PostgreSQL subnet, Batch subnet

Added wiring for PostgreSQL Manager and BatchManager, which aren't built into the latest version of ARM.

Updated existing tests for ARM, factories. Added an integration test for the Cromwell Landing Zone factory.

In Progress: Fixing Cromwell LZFactory Integration test

Still needed: Separate PR with an LZFactory method for shutting down resources.

2022-08-03 01:13 UTC, giventocode requested changes
Great progress. Left some comments.

2022-08-03 01:13 UTC, giventocode commented on src/main/java/bio/terra/cloudres/azure/landingzones/definition/factories/CromwellBaseResourcesFactory.java
> +      var aks =
I don't see the configuration to deploy the AKS node pool in subnet.  I think this will require that you create the VNet first and then you use the VNet/Subnet id to complete the configuration of the AKS cluster.  For this scenario, you can implement a `prerequisite` deployment.  [Check Handling Prerequisites](https://github.com/DataBiosphere/terra-cloud-resource-lib/tree/feature/TOAZ-169-migrate-crl-to-java-17/docs/landingzones#handling-prerequisites)

2022-08-03 01:13 UTC, giventocode commented on src/main/java/bio/terra/cloudres/azure/landingzones/definition/factories/LandingZoneDefinitionProviderImpl.java
> +          .getDeclaredConstructor(
Related to my earlier comment, this could've been avoided if I had used the client wrapper -if possible, let's make the change so going forward adding more clients is less painful.

2022-08-03 01:13 UTC, giventocode commented on src/test/java/bio/terra/cloudres/azure/landingzones/definition/factories/TestLandingZoneFactory.java
> +import static bio.terra.cloudres.azure.landingzones.definition.ResourceNameGenerator.*;
Wildcard imports are not preferred.

2022-08-03 01:13 UTC, giventocode commented on src/main/java/bio/terra/cloudres/azure/landingzones/definition/factories/CromwellBaseResourcesFactory.java
> +      var postgres =
Same as AKS, I don't see any configuration to deploy the postgres server inside its subnet - it may also require the deployment of a private link.

2022-08-08 19:33 UTC, giventocode requested changes

2022-08-08 20:52 UTC, jordansafer commented on src/main/java/bio/terra/cloudres/azure/landingzones/definition/factories/CromwellBaseResourcesFactory.java
> +      Networks listNetworks = azureResourceManager.networks();
Makes sense! I switched back an forth a bit while debugging, since it was a convenient sanity check to call ARM a second time and make sure the resource was created. Fixing-

2022-08-08 22:14 UTC, jordansafer commented on src/main/java/bio/terra/cloudres/azure/landingzones/definition/factories/CromwellBaseResourcesFactory.java
> +      Networks listNetworks = azureResourceManager.networks();
Fixed- note that for subnets, there's still one call to ARM required, because we don't propogate subnet ids as part of `prerequisites`

2022-08-10 15:51 UTC, giventocode approved these changes
LGTM!

2022-08-10 15:51 UTC, merged