[TERRA-384] Add basic AWS endpoint wrappers
DataBiosphere/terra-cloud-resource-lib pull request #158
Opened 2023-04-04 18:47 UTC by zloery

This wraps basic SageMaker notebook and S3Bucket endpoints to CRL in order to log requests and record metrics for these calls.

Because these are generally thin wrappers, this is tested entirely via unit tests which do not talk to AWS infrastructure. Services using this library should write integration/connected tests as needed to verify AWS behavior.

2023-04-04 21:41 UTC, jmczerk requested changes
One change requested, but otherwise looks great.  Thanks for taking this on!

2023-04-04 21:41 UTC, jmczerk commented on src/main/java/bio/terra/cloudres/aws/bucket/S3BucketCow.java
> +  public ListObjectsV2Response listBlobs(String bucketName, String prefix) {
The `ListObjectV2` API has a limit of 1,000 object returned per call.  We'll want to plumb the ability to optionally pass a [continuation token](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/ListObjectsV2Request.Builder.html#continuationToken(java.lang.String)) in case the response comes back as truncated and containing a continuation token, in case we need to iterate more than 1,000 object.

2023-04-04 21:41 UTC, jmczerk commented on src/main/java/bio/terra/cloudres/aws/notebook/SageMakerNotebookCow.java
> +  /**
`s/start/stop`
`s/usable/stopped`

2023-04-05 19:02 UTC, jmczerk approved these changes

2023-04-10 14:25 UTC, dexamundsen approved these changes

2023-04-10 15:13 UTC, merged