[PF-412] Add custom role endpoint support
DataBiosphere/terra-cloud-resource-lib pull request #65
Opened 2021-02-10 17:40 UTC by zloery

This change adds wrappers around Google's [custom role management endpoints](https://cloud.google.com/iam/docs/reference/rest/v1/projects.roles) to the IAM CRL to support creating, deleting, patching, getting, and deleting custom roles on a project-level.

This does not wrap organization-level custom role endpoints. Those are similar, but we do not currently have a usecase for them.

2021-02-10 18:14 UTC, yonghaoy approved these changes
you will also need to update version here, https://github.com/DataBiosphere/terra-cloud-resource-lib/blob/master/google-iam/gradle.properties
Then manually publish library after merge

2021-02-10 18:14 UTC, yonghaoy commented on google-iam/src/main/java/bio/terra/cloudres/google/iam/IamCow.java
> +          result.addProperty("parent", parent);
this serialize is used to log entire request.  I think it would be useful if we can log view if it has it.  
Maybe make an Optional<String> for that, and serialize it if present?

2021-02-10 20:08 UTC, wchamber requested changes

2021-02-10 20:08 UTC, wchamber commented on google-iam/src/test/java/bio/terra/cloudres/google/iam/IamCowTest.java
> +      retryNum++;
nit: use a for loop for retryNum?
I'm sad this takes up to 18seconds.

2021-02-10 20:08 UTC, wchamber commented on google-iam/src/test/java/bio/terra/cloudres/google/iam/IamCowTest.java
> +   * @return
nit: remove the empty `@return` block?

2021-02-10 20:09 UTC, wchamber commented on google-iam/src/main/java/bio/terra/cloudres/google/iam/IamCow.java
> +          result.addProperty("parent", parent);
there exists List#getView  https://developers.google.com/resources/api-libraries/documentation/iam/v1/java/latest/com/google/api/services/iam/v1/Iam.Projects.Roles.List.html#getView--

2021-02-10 22:45 UTC, zloery commented on google-iam/src/main/java/bio/terra/cloudres/google/iam/IamCow.java
> +          result.addProperty("parent", parent);
Restructured this a bit, view is now a field and will be serialized

2021-02-10 22:46 UTC, zloery commented on google-iam/src/main/java/bio/terra/cloudres/google/iam/IamCow.java
> +          return this;
This is mostly an issue of the underlying `Iam.Projects.Roles.List` object not being exposed. I switched to making that visible to `AbstractRequestCow`s, let me know if there's a better way to structure this

2021-02-10 22:49 UTC, zloery commented on google-iam/src/test/java/bio/terra/cloudres/google/iam/IamCowTest.java
> +      retryNum++;
I haven't actually timed it, this was mainly for consistency with above. I'm not sure what the expected duration is, other than definitely not 18s

2021-02-11 17:21 UTC, wchamber requested changes

2021-02-11 17:21 UTC, wchamber commented on google-iam/src/main/java/bio/terra/cloudres/google/iam/IamCow.java
> +          return this;
Sorry, there's a pattern for this. Basically, it's cows all the way down. While we don't want to expose the underlying List object through our wrapping Cow, it's expected and correct to wrap its methods. In this case, our List COW takes the underlying List in it's constructor. We should store the underlying list as a `private final Iam.Projects.Roles.List list;` here in our List COW class. Then, our COW List setView is 
```
public List setView(String view) {
          list.setView(view);
          return this;
}
```
Similarly, in the serialize we can use `list.getView()`.
Example: https://github.com/DataBiosphere/terra-cloud-resource-lib/blob/de4de2e29cc62330b49cceb2a1976eb2c452caeb/google-serviceusage/src/main/java/bio/terra/cloudres/google/serviceusage/ServiceUsageCow.java#L100-L127

2021-02-11 18:09 UTC, zloery commented on google-iam/src/main/java/bio/terra/cloudres/google/iam/IamCow.java
> +          return this;
Ah perfect, I was looking for how other cows did this but didn't see anything. That approach makes sense to me

2021-02-11 18:40 UTC, wchamber approved these changes
thanks!

2021-02-11 19:17 UTC, merged