[WIP] Add Azure resource deployments
DataBiosphere/terra-cloud-resource-lib pull request #98
Opened 2021-08-23 19:25 UTC by rtitle

This PR adds an `azure-resource-manager` module used for Azure resource deployments. It includes a unit test which:
* Authenticates as a publisher identity
* Deploys a Data Science VM template to the consumer's managed resource group
* Verifies the deployment succeeded
* Deletes the deployed resources

Still TODO:
* String constants are stubbed out (ping Rob for some real values). How should we handle seed data in Azure integration tests?
* Resource deletion could use some work. Right now the test nukes all resources in the managed resource group but there's probably a need to delete things more granularly based on tags.
* Test with new templates as we update them in https://github.com/DataBiosphere/terra-azure-arm-templates

2021-08-23 20:07 UTC, mcovarr commented on azure-resource-manager/src/main/java/bio/terra/cloudres/azure/resouce/manager/AzureResourceConfiguration.java
> +package bio.terra.cloudres.azure.resouce.manager;
resouce => resource

2021-08-23 20:23 UTC, Qi77Qi commented on azure-resource-manager/src/test/resources/azuredeploy.json
> +{
can the test reference a template from https://github.com/DataBiosphere/terra-azure-arm-templates/tree/main/leonardo instead of committing this one in this repo?

2021-08-23 20:23 UTC, Qi77Qi commented on settings.gradle
> +        'platform', 'azure-resource-manager'
it's essentially an ARM template deployment helper right?

2021-08-23 20:27 UTC, mcovarr commented on azure-resource-manager/src/test/resources/azuredeploy.json
> +        "description": "The name of you Virtual Machine."
you => your

2021-08-23 20:44 UTC, rtitle commented on azure-resource-manager/src/test/resources/azuredeploy.json
> +{
Yeah good idea, that probably makes more sense 👍

2021-08-23 20:49 UTC, rtitle commented on settings.gradle
> +        'platform', 'azure-resource-manager'
ARM == Azure Resource Manager :) 

`azure-resource-manager` is basically the Azure resource SDK. It can deploy templates (JSON) or individual resources via Java SDK. Right now in this PR there are only template deployments, but I think we'll end up having direct Java SDK calls too. I feel like it can all live under the `azure-resource-manager` module (unless we find a good reason to split them..)

2021-08-23 20:52 UTC, rtitle commented on settings.gradle
> +        'platform', 'azure-resource-manager'
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview

2021-08-23 20:58 UTC, Qi77Qi commented on settings.gradle
> +        'platform', 'azure-resource-manager'
> I feel like it can all live under the azure-resource-manager module (unless we find a good reason to split things into separate modules..).

Yea, I wasn't sure if this module is intended to be an "all-in-one" module, or an `ARM` only module similar to the other modules in this repo.

this repo seems to split things, so it might be confusing if we bundle everything in this module...altho maybe we don't really need much more than ARM since ARM template is pretty powerful

2021-08-23 21:02 UTC, Qi77Qi commented on azure-resource-manager/build.gradle
> +    implementation group: 'com.azure.resourcemanager', name: 'azure-resourcemanager', version: '2.7.0'
is https://github.com/Azure/azure-sdk-for-java the github repo? might be useful to link the repo as well

2021-08-23 21:18 UTC, rtitle commented on settings.gradle
> +        'platform', 'azure-resource-manager'
Yeah.. maybe it makes sense to split the CRL modules based on Azure library, similar to GCP.

E.g. the template deployment stuff is (confusingly) in `azure-resourcemanager-resources` (https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager/azure-resourcemanager-resources).

Whereas compute calls are in `azure-resourcemanager-compute` (https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager/azure-resourcemanager-compute).

Will try to organize this…

2021-08-24 17:56 UTC, rtitle commented
Thanks @yonghaoy! I'll do another pass on this PR to try and clean some of this stuff up, then maybe we can discuss more from there.

2021-08-25 16:31 UTC, jdcanas commented on azure-resource-manager/src/main/java/bio/terra/cloudres/azure/resouce/manager/AzureResourceConfiguration.java
> +public class AzureResourceConfiguration {
FYI, I wrote some of this code.

This is mainly here because muscles (@nmalfroy) had some code I used as a boilerplate. I'll be using this code shortly in a subsequent PR. 

That being said, I included it because I thought it was a good wrapper. There are different ways too configure an `AzureResourceManager` with various tenants (i.e. the home or user tentants) and subscriptions, so it felt good to have a class with readable methods. This could theoretically be handled a bit clearer with various constructors, but this class follows a common pattern we use where we have an object/class whose purpose is to create a client and handle initial config. See [this](https://github.com/broadinstitute/workbench-libs/blob/develop/google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleDataprocService.scala#L99) in workbench-libs

2021-08-25 16:37 UTC, jdcanas commented on azure-resource-manager/src/main/java/bio/terra/cloudres/azure/resouce/manager/AzureResourceConfiguration.java
> +public class AzureResourceConfiguration {
Hmm.. though I see @rtitle isn't using it as such here https://github.com/DataBiosphere/terra-cloud-resource-lib/pull/98/files#diff-c4c51513c4cd784e9d8bc0cd8b7bc114fdb5e4516449db964cb6842894b5e339R51 and is creating the client directly instead of using `azureResourceConfiguration.getClient()`. We should probably make the constructor private/protected, and maybe make `getClient` more descriptive.

2021-08-30 20:58 UTC, rtitle commented
@wchamber I think this is ready for some eyes, interested to hear your thoughts.

2021-09-01 17:03 UTC, wchamber requested changes

2021-09-01 17:03 UTC, wchamber commented on azure-resourcemanager-resources/src/test/java/bio/terra/cloudres/azure/resourcemanager/resources/ResourceManagerCowTest.java
> +            "https://raw.githubusercontent.com/DataBiosphere/terra-azure-arm-templates/main/leonardo/datascience-vm-customization/azuredeploy.json");
I don't think CRL should be testing a "real" deployment template. A CRL test should have a dummy deployment template for the purposes of testing so that we're not broken by changes to an external repo.
Whether the template referenced here is a good one is a test for that repo, not CRL. CRL wants to be agnostic about its use.

2021-09-01 17:03 UTC, wchamber commented on azure-resourcemanager-resources/src/test/java/bio/terra/cloudres/azure/resourcemanager/resources/ResourceManagerCowTest.java
> +  private void cleanResourceGroup() throws IOException {
Not this PR: This will inevitably leak resources during development, but fine for initial PR. Let's talk about using Janitor for cleanup.

2021-09-01 19:11 UTC, rtitle commented
Thanks for the review @wchamber! I'll process this/respond tomorrow or Fri.

2021-09-03 12:36 UTC, rtitle commented on azure-resourcemanager-resources/src/main/java/bio/terra/cloudres/azure/resourcemanager/resources/ResourceManagerCow.java
> +                .create(),
This is really helpful, thank you! Will look into options.

2021-09-03 13:30 UTC, rtitle commented on azure-resourcemanager-resources/src/main/java/bio/terra/cloudres/azure/resourcemanager/resources/ResourceManagerCow.java
> +                .create(),
There is one thing I struggled with trying to wrap the Azure fluent API. For Google (`com.google.api.services`), all the operations (such as `Bigquery.Datasets.Get`) extend from `AbstractGoogleClientRequest<T>`. So we can decorate everything with `AbstractRequestCow<T>` which _wraps_ `AbstractGoogleClientRequest<T>` and plug in our logging.

For the Azure fluent API, I couldn't find such a common base class for _all_ operations. This makes it harder to just decorate things and inject `OperationAnnotator::exececuteCloudOperation` for cloud calls. There might be a creative way to do this though, need to spend more time with it.

I totally take the point of not hiding the cloud API, and just decorating it with our logging. Will see if I can make this work for Azure, also thinking a "CRL Azure Support" design doc would be useful since CRL is a bit more subtle than I thought initially. :)

2021-09-03 13:43 UTC, rtitle commented on azure-resourcemanager-resources/src/main/java/bio/terra/cloudres/azure/resourcemanager/resources/ResourceManagerCow.java
> +                .create(),
I guess there are probably a small set of base classes (`Creatable`, `Deletable`) that we could wrap with Cows…

2021-09-03 13:45 UTC, wchamber commented on azure-resourcemanager-resources/src/main/java/bio/terra/cloudres/azure/resourcemanager/resources/ResourceManagerCow.java
> +                .create(),
Yep, a doc SG.
\For GCP, it's not true that "everything' has a common base class, just the very raw auto generated libraries from `com.google.api.services`. google-storage, for example, has a `com.google.cloud` hand crafted library. There, we're wrapping objects that have cloud call methods on them without any base class, e.g. `BlobCow` and `BucketCow`. But that let's extreme than the number of classes to wrap for the fluent API. https://github.com/DataBiosphere/terra-cloud-resource-lib/tree/master/google-storage/src/main/java/bio/terra/cloudres/google/storage

2021-09-03 14:29 UTC, rtitle commented
Per offline discussion, I think I'm going to close this PR. Will follow up with a design doc w.r.t. CRL Azure support.

2021-09-03 14:29 UTC, closed without merging